# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu_minisys.xdc

# IP: ip/prgrom/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet
